server:
  port: 8082

spring:
  application:
    name: product

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://ec2-13-124-222-121.ap-northeast-2.compute.amazonaws.com/eureka  # default address